# Machine Learning 
### Objective: Use past data to predict future data. 

#### Note:
- What are methods


#### Machine Learning general template:
1. Import libraries (essentially code that other people have already written - you can just import and use the methods to make your life easier)
2. Load the dataset - as a pandas dataframe 
3. Analyse the data (know which are your features and which is the target variable - thing you are predicting) & Clean the data (may need to delete irrelevant stuff, missing values, remove outliers, etc.)
4. Shuffle the data to add to the randomness and remove possible patterns in the data
5. Split all the data into features and target class & Convert the loaded pandas dataframe into numpy arrays that can be used by scikit_learn (just something you gotta do)
6. Save your new clean numpy array data to use 
7. Normalise the data 
8. Within your features, split it into training_inputs, testing_inputs (usually 80/20 or 70/30 - depends on your data) & at the same time within your target, split into the training_classes, testing_classes 
9. There are many different classifiers that will do the bulk of the predicting for you - you just need to load your data into the classifier to train it - then get the accuracy score of each classifier that you test
10. When you have tested multiple, get the one with the highest score to make predictions with your testing data - using the testing data sets instead of the training data sets ensures that your classifier is seeing new data - makes sure it's accurate
11. Load in the testing data to get prediction and accuracy score 
12. With your classifier, you can create your own model to use when you want to predict new data 
13. Input own feature data and normalize it
14. Run the prediction and print the result 


## 1. Import libraries

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn import svm
from sklearn import linear_model

import joblib
from sklearn.model_selection import cross_val_score
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import utils

import pickle

## 2. Load the dataset

In [2]:
from scipy.io import loadmat 
xx=loadmat('./mu_60_new.mat')
df=xx['mu_60']
df2=xx['mu_60']
X=df[:,:8]
y=df2[:,8:9]

In [3]:
from sklearn.utils.validation import column_or_1d
y = column_or_1d(y, warn=True)

<ipython-input-3-ad95dc4354ea>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [4]:
y[1200]

75.562003

## 3. Normalize the data 
- Normalize the attribute data using preprocessing.StandardScaler() 
- Normalization means adjusting values measured on different scales to a common scale

In [5]:
scaler = preprocessing.StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[ 0.00725667,  0.39876199, -1.4318601 , ..., -2.42009345,
         1.26832292,  1.20342222],
       [-0.32907673,  0.07848312, -1.43012521, ..., -2.41924015,
         1.27034643,  1.20143779],
       [ 0.53791449, -0.2309387 , -1.42990835, ..., -2.41838607,
         1.26832292,  1.20342222],
       ...,
       [ 0.05957576, -0.05179878,  1.01650782, ...,  0.80185015,
        -1.08094216, -1.1005276 ],
       [ 0.08199641, -0.31779242,  1.01954389, ...,  0.80185015,
        -1.08094216, -1.1005276 ],
       [-0.06001074, -0.23636591,  1.01368862, ...,  0.80185015,
        -1.08094216, -1.1005276 ]])

## 4. Within your features, split it into training_inputs, testing_inputs, training_classes, testing_classes 
- X_train, X_validation, Y_train, Y_validation

In [6]:
seed = 18
(training_inputs,
 testing_inputs,
 training_target,
 testing_target) = train_test_split(X_scaled, 
                                     y, 
                                     test_size=0.20, 
                                     train_size=0.80, 
                                     random_state=seed)

## 5. Classifiers
- If the target you are trying to predict is a continuous data, you need to use 'best-fit-line' (regression) kind of classifiers
- If the target is a YES/NO kind of thing, you can use others
- In this case, it's the former, so must use regressor algorithms

In [7]:
classifiers = [
    svm.SVR(gamma='auto'),
    linear_model.SGDRegressor(),
    linear_model.BayesianRidge(),
    linear_model.LassoLars(),
    linear_model.ARDRegression(),
    linear_model.PassiveAggressiveRegressor(),
    linear_model.TheilSenRegressor(),
    linear_model.LinearRegression()]

In [8]:
# Loop through each classifier in the array above 
for classifier in classifiers:
    print("======================================================================")
    print(classifier)
    clf = classifier
    cv_scores = cross_val_score(clf, X_scaled, y, cv=10, scoring='neg_mean_absolute_error')
    print("----- SCORE -----")
    print(cv_scores.mean())
    print("======================================================================")

SVR(gamma='auto')
----- SCORE -----
-0.5231042667467978
SGDRegressor()
----- SCORE -----
-0.577563710902156
BayesianRidge()
----- SCORE -----
-0.5861662777484717
LassoLars()


/home/suleyman/anaconda3/envs/datascience/lib/python3.9/site-packages/sklearn/linear_model/_base.py:133: FutureWarning: The default of 'normalize' will be set to False in version 1.2 and deprecated in version 1.4.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LassoLars())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * np.sqrt(n_samples). 
  warnings.warn(
/home/suleyman/anaconda3/envs/datascience/lib/python3.9/site-packages/sklearn/linear_model/_base.py:133: FutureWarning: The default of 'normalize' will be set to False in version 1.2 and deprecated in version 1.4.
If you wish to scale the

----- SCORE -----
-0.42691540885224943
ARDRegression()
----- SCORE -----
-0.584983200596261
PassiveAggressiveRegressor()
----- SCORE -----
-1.0121942006175242
TheilSenRegressor()
----- SCORE -----
-0.576745338307493
LinearRegression()
----- SCORE -----
-0.5842785514867709


In [9]:
# Loop through each classifier in the array above 
for classifier in classifiers:
    print("======================================================================")
    print(classifier)
    clf = classifier
    cv_scores = cross_val_score(clf, X_scaled, y, cv=10, scoring='neg_root_mean_squared_error')
    print("----- SCORE -----")
    print(cv_scores.mean())
    print("======================================================================")

SVR(gamma='auto')
----- SCORE -----
-0.6615674946899829
SGDRegressor()
----- SCORE -----
-0.6797790451167105
BayesianRidge()
----- SCORE -----
-0.7085034706366431
LassoLars()


/home/suleyman/anaconda3/envs/datascience/lib/python3.9/site-packages/sklearn/linear_model/_base.py:133: FutureWarning: The default of 'normalize' will be set to False in version 1.2 and deprecated in version 1.4.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LassoLars())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * np.sqrt(n_samples). 
  warnings.warn(
/home/suleyman/anaconda3/envs/datascience/lib/python3.9/site-packages/sklearn/linear_model/_base.py:133: FutureWarning: The default of 'normalize' will be set to False in version 1.2 and deprecated in version 1.4.
If you wish to scale the

----- SCORE -----
-0.5348322005096687
ARDRegression()
----- SCORE -----
-0.7075250920787206
PassiveAggressiveRegressor()
----- SCORE -----
-0.9057001331618778
TheilSenRegressor()
----- SCORE -----
-0.6447279884327358
LinearRegression()
----- SCORE -----
-0.7071574594348466


## 6. Choose classifier with the highest score 
- Looks like svm.SVR is the best

## 7. Do prediction with test data using the selected classifier from above
- Make predictions with testing data

In [10]:
clf = svm.SVR(gamma='auto')

clf.fit(training_inputs, training_target)
predictions = clf.predict(testing_inputs)
print(predictions)

# There will be 200 predictions because 20% of 1000 is 200
print(len(predictions)) 

[75.30844123 75.23418673 75.38694842 ... 75.40657143 76.00136156
 75.38910336]
1580


## 8. Create model 
- Can use this model in other programs 

In [11]:
pickle.dump(clf, open('trained_sensor_model.pkl', 'wb'))

In [12]:
# Load the model 
clf_svm_model = pickle.load(open('trained_sensor_model.pkl', 'rb'))
clf_svm_model

SVR(gamma='auto')

## 9. Input own feature data and normalize it
-  'light_avg', 'humidity_avg', 'latitude', 'longitude', 'elevation'

In [13]:
X_scaled[1]

array([-0.32907673,  0.07848312, -1.43012521, -1.03928991, -2.45790369,
       -2.41924015,  1.27034643,  1.20143779])

In [14]:
X[1]

array([-2.04746000e-01,  2.32410000e-02,  1.07463000e-01,  1.71089000e-01,
        1.64904842e+03,  1.62490419e+03,  5.49769920e+01,  5.48823670e+01])

In [15]:
y[1]

75.648333

In [16]:
data = np.array([[-1.1430500e-01,  2.1028900e-01,  1.6401000e-02, -4.3494700e-01,
        8.3916729e+01,  8.1053279e+01,  3.1084237e+01,  3.0894988e+01]])
data_scaled = scaler.transform(data)
data_scaled

array([[ -0.16464711,   0.57247207,  -1.43207697,  -1.05277802,
        -94.35539289, -88.83218673,   0.24848692,   0.19532017]])

## 10. Run prediction 

In [17]:
# Make a prediction against prediction features
prediction = clf_svm_model.predict(data_scaled)

print("The predicted yaw rate:")
print(prediction)

The predicted yaw rate:
[75.47302532]
